[build]
builder = "nixpacks"
buildCommand = "cd chess-app && npm install && npm run build"

[deploy]
startCommand = "cd chess-app && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
workdir = "chess-app"
